#customer group routes

hecommerce_management_customergroup:
    path: /{_locale}/customergroup
    defaults:  { _controller: HeadooEcommerceBundle:CustomerGroup:index }
    methods:  GET
    requirements:
        _locale: "%hecommerce.routing.locales%"

hecommerce_management_customergroup_create:
    path: /{_locale}/customergroup
    defaults:  { _controller: HeadooEcommerceBundle:CustomerGroup:create }
    methods:  POST
    requirements:
        _locale: "%hecommerce.routing.locales%"
    
hecommerce_management_customergroup_new:
    path: /{_locale}/customergroup/new
    defaults:  { _controller: HeadooEcommerceBundle:CustomerGroup:new }
    methods:  GET
    requirements:
        _locale: "%hecommerce.routing.locales%"
    
hecommerce_management_customergroup_show:
    path: /{_locale}/customergroup/{id}
    defaults:  { _controller: HeadooEcommerceBundle:CustomerGroup:show }
    methods: GET
    requirements:
        id:  \d+
        _locale: "%hecommerce.routing.locales%"
    
hecommerce_management_customergroup_edit:
    path: /{_locale}/customergroup/{id}/edit
    defaults:  { _controller: HeadooEcommerceBundle:CustomerGroup:edit }
    methods: GET
    requirements:
        id:  \d+
        _locale: "%hecommerce.routing.locales%"
    
hecommerce_management_customergroup_update:
    path: /{_locale}/customergroup/{id}
    defaults:  { _controller: HeadooEcommerceBundle:CustomerGroup:update }
    methods: [POST, PUT]
    requirements:
        id:  \d+
        _locale: "%hecommerce.routing.locales%"
    
hecommerce_management_customergroup_delete:
    path: /{_locale}/customergroup/{id}
    defaults:  { _controller: HeadooEcommerceBundle:CustomerGroup:delete }
    methods: [POST, DELETE]
    requirements:
        id:  \d+
        _locale: "%hecommerce.routing.locales%"
    
