#service routes

hecommerce_management:
    path:     /{_locale}/management
    defaults: { _controller: "HeadooEcommerceBundle:Management:index" }
    methods:  GET
    requirements:
        _locale: "%hecommerce.routing.locales%"
