#order routes

hecommerce_order_delete:
    path: /{_locale}/order/{id}
    defaults:  { _controller: hecommerce.order.controller:deleteAction }
    methods: [POST, DELETE]
    requirements:
        id:  \d+
        _locale: "%hecommerce.locales%"

    
