#payment routes

hecommerce_payment_prepare_stripe:
    path:     /{_locale}/store/payment/stripe/prepare
    defaults: { _controller: "HeadooEcommerceBundle:Payment:prepareStripe" }
    methods:  GET
    requirements:
        _locale: "%hecommerce.routing.locales%"

hecommerce_payment_done_stripe:
    path:     /{_locale}/store/payment/done
    defaults: { _controller: "HeadooEcommerceBundle:Payment:doneStripe" }
    methods:  GET
    requirements:
        _locale: "%hecommerce.routing.locales%"

hecommerce_payment_prepare_offline:
    path:     /{_locale}/store/payment/offline/prepare
    defaults: { _controller: "HeadooEcommerceBundle:Payment:prepareOffline" }
    methods:  GET
    requirements:
        _locale: "%hecommerce.routing.locales%"

hecommerce_payment_done_offline:
    path:     /{_locale}/store/payment/offline/done
    defaults: { _controller: "HeadooEcommerceBundle:Payment:doneOffline" }
    methods:  GET
    requirements:
        _locale: "%hecommerce.routing.locales%"
        
