#service range routes

hecommerce_servicerange:
    path:     /{_locale}/servicerange
    defaults: { _controller: "HeadooEcommerceBundle:ServiceRange:index" }
    methods:  GET
    requirements:
        _locale: "%hecommerce.locales%"

hecommerce_servicerange_show:
    path:     /{_locale}/servicerange/{id}/show
    defaults: { _controller: "HeadooEcommerceBundle:ServiceRange:show" }
    requirements:
        id:  \d+
        _locale: "%hecommerce.locales%"

hecommerce_servicerange_new:
    path:     /{_locale}/servicerange/new
    defaults: { _controller: "HeadooEcommerceBundle:ServiceRange:new" }
    requirements:
        _locale: "%hecommerce.locales%"

hecommerce_servicerange_create:
    path:     /{_locale}/servicerange/create
    defaults: { _controller: "HeadooEcommerceBundle:ServiceRange:create" }
    methods:  POST
    requirements:
        _locale: "%hecommerce.locales%"

hecommerce_servicerange_edit:
    path:     /{_locale}/servicerange/{id}/edit
    defaults: { _controller: "HeadooEcommerceBundle:ServiceRange:edit" }
    requirements:
        id:  \d+
        _locale: "%hecommerce.locales%"

hecommerce_servicerange_update:
    path:     /{_locale}/servicerange/{id}/update
    defaults: { _controller: "HeadooEcommerceBundle:ServiceRange:update" }
    methods:  [POST, PUT]
    requirements:
        id:  \d+
        _locale: "%hecommerce.locales%"

hecommerce_servicerange_delete:
    path:     /{_locale}/servicerange/{id}/delete
    defaults: { _controller: "HeadooEcommerceBundle:ServiceRange:delete" }
    methods:  [POST, DELETE]
    requirements:
        id:  \d+
        _locale: "%hecommerce.locales%"
