services:

    #Controllers
    hecommerce.order.controller:
        class: EcommerceBundle\Controller\OrderController
        arguments: [ %headoo_ecommerce.order.entity%, @form.factory, @translator, @doctrine.orm.entity_manager, @router ]

    #Managers
    hecommerce.service.manager:
        class: EcommerceBundle\Model\ServiceManager
        arguments: [ @doctrine.orm.entity_manager, %headoo_ecommerce.service.entity% ]
    hecommerce.paymentmethod.manager:
        class: EcommerceBundle\Model\PaymentMethodManager
        arguments: [ @doctrine.orm.entity_manager, %headoo_ecommerce.paymentmethod.entity% ]
    hecommerce.ordereditem.manager:
        class: EcommerceBundle\Model\OrderedItemManager
        arguments: [ @doctrine.orm.entity_manager, %headoo_ecommerce.ordereditem.entity% ]
    hecommerce.order.manager:
        class: EcommerceBundle\Model\OrderManager
        arguments: [ @doctrine.orm.entity_manager, %headoo_ecommerce.order.entity%, @service_container ]
    hecommerce.confirmationemail.manager:
        class: EcommerceBundle\Model\ConfirmationEmailManager
        arguments: [ @doctrine.orm.entity_manager, %headoo_ecommerce.confirmationemail.entity% ]

    #Form Types
    hecommerce.form.type.customergroup:
        class: EcommerceBundle\Form\CustomerGroupType
        tags:
            - { name: form.type, alias: headoo_ecommercebundle_customergroup }
        arguments: [ %headoo_ecommerce.customergroup.entity%, %headoo_ecommerce.pricecurrency.entity% ]
    hecommerce.form.type.service:
        class: EcommerceBundle\Form\ServiceType
        tags:
            - { name: form.type, alias: headoo_ecommercebundle_service }
        arguments: [ %headoo_ecommerce.customergroup.entity%, %headoo_ecommerce.service.entity%, %headoo_ecommerce.servicerange.entity%]
    hecommerce.form.type.servicerange:
        class: EcommerceBundle\Form\ServiceRangeType
        tags:
            - { name: form.type, alias: headoo_ecommercebundle_servicerange }
        arguments: [ %headoo_ecommerce.servicerange.entity% ]
    hecommerce.form.type.pricecurrency:
        class: EcommerceBundle\Form\PriceCurrencyType
        tags:
            - { name: form.type, alias: headoo_ecommercebundle_pricecurrency }
        arguments: [ %headoo_ecommerce.pricecurrency.entity% ]
    hecommerce.form.type.paymentmethod:
        class: EcommerceBundle\Form\PaymentMethodType
        tags:
            - { name: form.type, alias: headoo_ecommercebundle_paymentmethod }
        arguments: [ %headoo_ecommerce.paymentmethod.entity% ]

    #Form Types FOS User Bundle
    hecommerce.form.registration:
        class: EcommerceBundle\Form\RegistrationType
        tags:
            - { name: form.type, alias: hecommerce_user_registration }
        arguments: [ %headoo_ecommerce.customergroup.entity% ]
    hecommerce.form.profile:
        class: EcommerceBundle\Form\ProfileType
        tags:
            - { name: form.type, alias: hecommerce_user_profile }
        arguments: [ %headoo_ecommerce.customergroup.entity% ]

    #Event Listener
    hecommerce.locale_listener:
            class: EcommerceBundle\EventListener\LocaleListener
            arguments: ["%kernel.default_locale%"]
            tags:
                - { name: kernel.event_subscriber }
         